POST http://localhost:3000/verifications/user HTTP/1.1
content-type: application/json

{
    "mobileNumber": "9898"
}

###

POST http://localhost:3000/verifications/otp HTTP/1.1
content-type: application/json

{
    "mobileNumber": 9898,
    "otpCode": 700110
}

###

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "bilal Ahmad",
    "mobileNumber": 34343,
    "City": "Isb",
    "address": "G 11 2",
    "location": []
}